packaging/linux/etc/observe-agent/connections/host_monitoring/logs.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/metrics.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml

OB-31723  Switched resource detection to /cloud version to add additional properties to resource on metrics,logs and resource dataset

fix: OB-31723 add additional host properties to linux config

---

.github/workflows/release.yml
.goreleaser.yaml

OB-32401: Update the release actions to cut a draft release vs. just publishing a tag

feat: update goreleaser task to cut draft release

---

.github/workflows/release-build.yaml

OB-9999: Disable build github action on PR

internal: stop running build on PR

---

cmd/commands/start/start.go
cmd/config/confighandler.go

OB-34510 feat: add --otel-config flag to read in additional otel config from file

feat: add --otel-config flag

---

packaging/docker/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/docker/observe-agent/otel-collector.yaml

OB-34551 feat: split out agent self-monitoring into connection for docker

feat: add self_monitoring to docker configs

---

packaging/docker/observe-agent/connections/host_monitoring/host.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/host.yaml
packaging/windows/connections/host_monitoring/host.yaml

OB-35568 Update polling interval of host filestats to 5m

fix: update polling interval for agent config filestats to 5m

---

cmd/commands/initconfig/initconfig.go
cmd/commands/initconfig/initconfig_test.go
cmd/connections/hostmonitoring.go

OB-35506 Update key delimiter for init-config + config handling to "::"

fix: update key references with new key delim "::"

---

components/processors/observek8sattributesprocessor/node.go
components/processors/observek8sattributesprocessor/noderoles.go
components/processors/observek8sattributesprocessor/nodestatus.go
components/processors/observek8sattributesprocessor/pod.go
components/processors/observek8sattributesprocessor/podcounts.go
components/processors/observek8sattributesprocessor/podreadiness.go
components/processors/observek8sattributesprocessor/podstatus.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/processor_test.go
components/processors/observek8sattributesprocessor/testdata/nodeObjectEventAlternativeRoleKey.json
components/processors/observek8sattributesprocessor/testdata/nodeObjectEventSimple.json
components/processors/observek8sattributesprocessor/testdata/podObjectEvent.json
components/processors/observek8sattributesprocessor/testdata/podObjectEventWithReadinessGates.json
events.json

Add "Status" and "Roles" facets
Rework the testing a bit to allow using jmespath to query specific fields of interest instead of manually creating json-like objects in go to exactly match the output.
This PR adds the "Roles" and "Status" facets to Node.
Since "Roles" is an array, I had to change the interface of the existing `ValueFn()` to return `any` instead of `string`, so that we can return maps and arrays, too.
The current testing process is a bit cumbersome and doesn't scale well, since we are making a single `pcommon.Logs` containing all testing input logs, and then we have to maintain a parallel slice of "desired outputs", correlating inLogs[i] with outResults[i]. Since the correlation is always 1:1, I figured I could change this to:
each testcase contains a single `pcommon.Logs`, …

OB-34960 Decorate k8s Node facets with custom processors

---

cmd/commands/initconfig/configschema.go
cmd/commands/initconfig/initconfig.go
cmd/commands/initconfig/initconfig_test.go
cmd/commands/initconfig/observe-agent.tmpl
cmd/connections/hostmonitoring.go
packaging/docker/observe-agent/connections/host_monitoring/host_metrics.yaml
packaging/docker/observe-agent/connections/host_monitoring/process_metrics.yaml
packaging/linux/config/observe-agent.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/host_metrics.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/process_metrics.yaml
packaging/windows/connections/host_monitoring/host_metrics.yaml
packaging/windows/connections/host_monitoring/process_metrics.yaml
packaging/windows/observe-agent.yaml

OB-34900 Split process level metrics collection out of host_monitoring metrics and default to off.

feat: split process metrics out of host metrics

---

components/processors/observek8sattributesprocessor/node.go
components/processors/observek8sattributesprocessor/noderoles.go
components/processors/observek8sattributesprocessor/nodestatus.go
components/processors/observek8sattributesprocessor/pod.go
components/processors/observek8sattributesprocessor/podconditions.go
components/processors/observek8sattributesprocessor/podcounts.go
components/processors/observek8sattributesprocessor/podreadiness.go
components/processors/observek8sattributesprocessor/podstatus.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/processor_test.go
components/processors/observek8sattributesprocessor/testdata/podObjectEvent.json
components/processors/observek8sattributesprocessor/types.go

Refactor processor actions to improve efficiency
- Unmarshal each event only once rather than once per action!
- Separate NodeActions and PodActions.
- For each event, call ComputeAttributes only on those actions that are able to process such event type!
Add Pod facet "conditions"

Refactor processor actions

---

components/processors/observek8sattributesprocessor/cronjobactions.go
components/processors/observek8sattributesprocessor/cronjobactions_test.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/testdata/cronJobEvent.json
components/processors/observek8sattributesprocessor/testdata/cronJobEventNotActive.json
components/processors/observek8sattributesprocessor/types.go

Add support for writing custom processors for the "CronJob" entity.
Add custom processor to compute CronJob "active" facet

feat: Add CronJob custom processor

---

components/processors/observek8sattributesprocessor/daemonsetactions.go
components/processors/observek8sattributesprocessor/endpointsactions.go
components/processors/observek8sattributesprocessor/endpointsactions_test.go
components/processors/observek8sattributesprocessor/ingressactions.go
components/processors/observek8sattributesprocessor/ingressactions_test.go
components/processors/observek8sattributesprocessor/nodeactions.go
components/processors/observek8sattributesprocessor/persistentvolumeactions.go
components/processors/observek8sattributesprocessor/persistentvolumeactions_test.go
components/processors/observek8sattributesprocessor/persistentvolumeclaimactions.go
components/processors/observek8sattributesprocessor/persistentvolumeclaimactions_test.go
components/processors/observek8sattributesprocessor/podactions.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/serviceaccountactions.go
components/processors/observek8sattributesprocessor/serviceaccountactions_test.go
components/processors/observek8sattributesprocessor/statefulsetactions.go
components/processors/observek8sattributesprocessor/statefulsetactions_test.go
components/processors/observek8sattributesprocessor/testdata/endpointsEvent.json
components/processors/observek8sattributesprocessor/testdata/ingressEvent.json
components/processors/observek8sattributesprocessor/testdata/persistentVolumeAWSElasticBlockStoreEvent.json
components/processors/observek8sattributesprocessor/testdata/persistentVolumeClaimEvent.json
components/processors/observek8sattributesprocessor/testdata/persistentVolumeHostPathEvent.json
components/processors/observek8sattributesprocessor/testdata/serviceAccountEvent.json
components/processors/observek8sattributesprocessor/testdata/statefulSetEvent.json
components/processors/observek8sattributesprocessor/types.go

Add actions to compute the "selector" facet for StatefulSet and PersistentVolumeClaim

feat: Add processor actions for new resources

---

components/processors/observek8sattributesprocessor/configmapactions.go
components/processors/observek8sattributesprocessor/configmapactions_test.go
components/processors/observek8sattributesprocessor/daemonsetactions.go
components/processors/observek8sattributesprocessor/deploymentactions.go
components/processors/observek8sattributesprocessor/deploymentactions_test.go
components/processors/observek8sattributesprocessor/ingressactions.go
components/processors/observek8sattributesprocessor/jobactions.go
components/processors/observek8sattributesprocessor/nodeactions.go
components/processors/observek8sattributesprocessor/persistentvolumeactions.go
components/processors/observek8sattributesprocessor/persistentvolumeclaimactions.go
components/processors/observek8sattributesprocessor/podactions.go
components/processors/observek8sattributesprocessor/podactions_test.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/serviceaccountactions.go
components/processors/observek8sattributesprocessor/serviceaccountactions_test.go
components/processors/observek8sattributesprocessor/serviceactions.go
components/processors/observek8sattributesprocessor/statefulsetactions.go
components/processors/observek8sattributesprocessor/testdata/configMapEvent.json
components/processors/observek8sattributesprocessor/testdata/deploymentEvent.json
components/processors/observek8sattributesprocessor/testdata/podTestEvent.json
components/processors/observek8sattributesprocessor/types.go

OTTL's `Len()` doesn't work well with some of the slices obtained by unmarshalling k8s events into their respective API entities. This is because `Len()` doesn't support the type of the inner elements of most of the slices we have to use.
As a result, the only way to "calculate" such lengths is via custom code in our events' processor.

feat: implement custom processor actions for all facets that involve calculating the length of a pcommon.Slice

---

scripts/install.ps1

OB-36354 Modify windows install script copying files to work the same for initial install and upgrading

fix: update file copying to work for upgrades

---

packaging/linux/config/observe-agent.yaml
packaging/windows/observe-agent.yaml

OB-36510 Update example observe-agent.yaml with comments

fix: update example observe-agent.yaml

---

components/processors/observek8sattributesprocessor/configmapactions_test.go
components/processors/observek8sattributesprocessor/cronjobactions_test.go
components/processors/observek8sattributesprocessor/daemonsetactions_test.go
components/processors/observek8sattributesprocessor/deploymentactions_test.go
components/processors/observek8sattributesprocessor/endpointsactions_test.go
components/processors/observek8sattributesprocessor/ingressactions_test.go
components/processors/observek8sattributesprocessor/jobactions_test.go
components/processors/observek8sattributesprocessor/nodeactions_test.go
components/processors/observek8sattributesprocessor/persistentvolumeactions_test.go
components/processors/observek8sattributesprocessor/persistentvolumeclaimactions_test.go
components/processors/observek8sattributesprocessor/podactions_test.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/processor_test.go
components/processors/observek8sattributesprocessor/secretactions.go
components/processors/observek8sattributesprocessor/secretactions_test.go
components/processors/observek8sattributesprocessor/serviceaccountactions_test.go
components/processors/observek8sattributesprocessor/serviceactions_test.go
components/processors/observek8sattributesprocessor/statefulsetactions_test.go
components/processors/observek8sattributesprocessor/testdata/secretEvent.json
components/processors/observek8sattributesprocessor/types.go

Add whole processor framework to modify an event body in place. The set of actions that do that are also type-specific, meaning that we only run relevant actions on any given event, based on the object type.
These actions modify the unmarshalled object IN PLACE and BEFORE the attributes-computing actions do their thing. This is mainly to allow secrets' obfuscation, where we want to prevent secret stuff to end up in the attributes by mistake.
Add secret "body" actions that obfuscate the secrets in "data".

fix: OB-37389 Obfuscate secrets in YAML body

---

components/processors/observek8sattributesprocessor/processor_test.go
components/processors/observek8sattributesprocessor/secretactions.go
components/processors/observek8sattributesprocessor/secretactions_test.go
components/processors/observek8sattributesprocessor/testdata/secretEventPrevConfig.json

Secret entities not only contain secrets in data, but might also contain
an annotation that represents the previous configuration for this
Secret, including the secrets. Drop such annotation

fix: OB-37389 Obfuscate secrets inside Secret previous configuration

---

components/processors/observek8sattributesprocessor/cronjobactions.go
components/processors/observek8sattributesprocessor/cronjobactions_test.go

Rename CronJob's "active" facet to "activeJobs" for easier understanding/handling

fix: OB-37441 Rename CronJob facet

---

README.md

Updating stale Go version reference in README

fix: update go version in the README

---

internal/root/root.go

OB-37820 Here's how it looks now:
```
$ ./observe-agent help
Observe distribution of OTEL Collector along with CLI utils to help with setup
and maintenance. To start the agent, run: observe-agent start
Usage:
observe-agent [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
diagnose    Run diagnostic checks.
help        Help about any command
init-config Initialize agent configuration
start       Start the Observe agent process.
status      Display status of agent
version     Display the currently installed version of the observe-agent.
Flags:
--config string   config file path
-h, --help            help for observe-agent
-t, --toggle          Help message for toggle
Use "observe-agent [command] --help" for more information about a command. …
```

fix: add a description to the root command

---

internal/commands/diagnose/configcheck.go
internal/commands/diagnose/configcheck.tmpl
internal/commands/diagnose/configcheck_test.go
internal/commands/diagnose/diagnose.go

OB-37709 add a new check to the diagnose command to check if the config file is valid YAML.

feat: add YAML parse check to diagnose command

---

.github/workflows/release-nightly.yaml

Adding @obs-gh-mattcotter to the list for release-nightly.yaml
Example run without this change where the release is skipped: https://github.com/observeinc/observe-agent/actions/runs/11448694510

fix: allow more users to trigger the Github nightly build action

---

components/processors/observek8sattributesprocessor/ingressactions.go
components/processors/observek8sattributesprocessor/ingressactions_test.go
components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/testdata/ingressEvent2.json
components/processors/observek8sattributesprocessor/tmp.json

We used to only return which host(s) each rule would apply to.
This PR enhances the formatting of ingress rules, returning them as a JSON object with more information, such as the URL path they are defined on and which serviceName:port the rules are for.

feat: Improve generation of Ingress rules

---

internal/commands/diagnose/diagnose.go
internal/commands/diagnose/otelconfigcheck.go
internal/commands/diagnose/otelconfigcheck.tmpl

OB-31850 Validate all OTEL configuration in the `diagnose` command
Example output:
> ⚠️ OTEL configuration validation failed with error service::pipelines::metrics: references receiver "filelog" which is not configured

feat: validate the otel configuration in diagnose

---

internal/commands/config/config.go
internal/commands/start/start.go
internal/commands/util/logger.go
internal/connections/confighandler.go
internal/connections/connections.go
internal/connections/hostmonitoring.go
internal/connections/selfmonitoring.go
internal/root/root.go
main.go

OB-37220 add a new config command to print out all configuration
This naming matches the `datadog-agent config` command. Having this will facilitate debugging as we start to add templated data to our OTEL config fragments.

feat: add new config command to print out all configuration

---

components/processors/observek8sattributesprocessor/processor.go
components/processors/observek8sattributesprocessor/processor_test.go
components/processors/observek8sattributesprocessor/types.go

Currently we were modifying the marshalled k8s object and then overriding the log body with its unmarshalled string representation.
This doesn't work well when the custom processor is not last in the pipeline, because other processors might have to index into the structured body to be able to extract values.
Since we need to move the transform processor after the custom processor in the agent configmap, we want to make sure that this processor leaves the log body as a structured object, rather than a plain string.

fix: Override log body with structured object

---

integration/modules/create_ec2/locals.tf

Previous Windows 2016 AMI is no longer being used. Update to new AMI

ci: update windows 2016 ami

---

internal/commands/config/config.go

OB-37220 add computed viper config output to config command.
This makes it easier to see when env vars are substituted for values in the config file.
Ex:
```
$ TOKEN="test_token" ./observe-agent config
enabled: true
logs:
enabled: true
metrics:
host:
enabled: true
process:
enabled: false
observe_url: ""
otelconfigfile: ""
self_monitoring:
enabled: true
token: test_token
```

feat: add computed viper config output to config command

---

internal/commands/initconfig/initconfig.go
internal/commands/initconfig/initconfig_test.go
internal/commands/initconfig/observe-agent.tmpl
internal/config/configschema.go
packaging/docker/observe-agent/connections/host_monitoring/logs.yaml
packaging/linux/config/observe-agent.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/logs.yaml

OB-37220 add include field to observe agent config that propagates to OTEL host log receiver
This is like #120 (which was closed accidentally), but also includes changes to `init-config` to handle default log files.
This enables us to use the agent config to list logs files.
Ex:
```yaml
enabled: true
logs: 
enabled: true
include: ["/log/test.log"]
receivers:
filelog/host_monitoring:
include:
- /log/test.log
```
Without the `include` specified in the agent config, we still get the correct defaults, ie:
```
receivers:
filelog/host_monitoring:
include:
- /var/log/**/*.log
- /var/log/syslog
```

feat: add include field to observe agent config that propagates to OTEL host log receiver

---

internal/config/configschema.go
internal/connections/confighandler.go
internal/connections/connections.go
packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

OB-36552 add agent-config var to override default resourcedetection/cloud::detectors
**Example**
With no agent config changes, the detectors are defaulted:
```yaml
resourcedetection/cloud:
detectors: ["gcp", "ecs", "ec2", "azure"]
```
But after adding this to the agent config:
```yaml
cloud_resource_detectors:
- azure
- ec2
```
The detectors become
```yaml
resourcedetection/cloud:
detectors:[azure,ec2]
```

feat: add agent-config var to override default resourcedetection/cloud::detectors

---

.github/workflows/generate-changelog.yaml
.github/workflows/release-build.yaml
.github/workflows/release-nightly.yaml
.github/workflows/release.yaml
.github/workflows/tests-integration.yaml
.goreleaser.yaml

OB-38483 skip deb and rpm publishing on nightly release
I will test this by running the action when this change lands.

fix: skip deb and rpm publishing on nightly release

---

integration/README.md
integration/scripts/test_configure.py
integration/scripts/test_diagnose.py
integration/scripts/test_ec2_connection.py
integration/scripts/test_install.py
integration/scripts/test_start.py
integration/scripts/test_version.py
integration/scripts/utils.py
integration/tests/integration.tftest.hcl
internal/commands/diagnose/agentstatuscheck.go
internal/commands/diagnose/agentstatuscheck.tmpl
internal/commands/diagnose/authcheck.go
internal/commands/diagnose/authcheck.tmpl
internal/commands/diagnose/configcheck.go
internal/commands/diagnose/configcheck.tmpl
internal/commands/diagnose/configcheck_test.go
internal/commands/diagnose/diagnose.go
internal/commands/diagnose/otelconfigcheck.go
internal/commands/diagnose/otelconfigcheck.tmpl
internal/commands/start/start.go
internal/commands/version/version.go
internal/connections/confighandler.go
internal/root/root.go
main_windows.go
packaging/linux/config/observe-agent.yaml

OB-32327 add new diagnostic check to validate the agent status, update integration tests to separate config initialization from running the diagnose check

feat: add new diagnostic check to validate the agent status

---

integration/scripts/test_configure.py
internal/commands/initconfig/initconfig.go
internal/commands/initconfig/initconfig_test.go
internal/commands/initconfig/observe-agent.tmpl
internal/connections/templatefuncs.go
internal/connections/templatefuncs_test.go
internal/connections/test/testHelloWorld.yaml
packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

fix whitespace typo when customizing CloudResourceDetectors. Before this change, the generated config was `detectors:[ec2]` instead of `detectors: [ec2]`

fix: fix whitespace typo when customizing CloudResourceDetectors

---

scripts/install_linux.sh

Add linux install script for manual installation support. This can install from a local zip or from our release downloads.
Examples:
```
$ bash ./scripts/install_linux.sh 
Downloading latest release from GitHub
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34.0M  100 34.0M    0     0  42.6M      0 --:--:-- --:--:-- --:--:-- 42.6M
Creating system install folders. This may ask for your password...
Leaving existing observe-agent.yaml in place.
Observe agent successfully installed to /etc/observe-agent
$ observe-agent version
Using config file: …
```

feat: add linux install script for manual installation support

---

internal/commands/config/config.go
internal/commands/start/start.go
internal/connections/confighandler.go

OB-38640 allow OTEL_CONFIG_OVERRIDES env var to replace agent config overrides
This will allow the agent to be fully run with env variables only.
example:
```sh
$ OTEL_CONFIG_OVERRIDES=`cat tmp.yml` ./observe-agent config
enabled: true
logs:
enabled: true
include: []
metrics:
host:
enabled: true
process:
enabled: false
observe_url: ""
otelconfigfile: ""
self_monitoring:
enabled: true
token: ""
processors:
probabilistic_sampler:
sampling_percentage: 50
service:
pipelines:
logs/forward:
exporters:
- debug
processors:
- probabilistic_sampler
receivers:
- otlp
```

fix: allow OTEL_CONFIG_OVERRIDES env var to replace agent config overrides

---

packaging/docker/compose-linux-host.yaml
packaging/docker/observe-agent/observe-agent.yaml

Add env var example to docker-compose, add agent config to image.
The goal of this change is to make Docker usage more clear.

feat: add env var example to docker-compose, add agent config to image

---

scripts/install_mac.sh

Update mac install script to download from latest release. Now that we have a new release which builds the expected Mac zip, we can finally download and install from GitHub.

feat: update mac install script to download from latest release

---

internal/commands/config/config.go
internal/config/configschema.go
internal/connections/connections.go
packaging/docker/observe-agent/connections/host_monitoring/logs.yaml

OB-40043: Correctly handle viper env var overrides for slice fields. We need this to specify host log overrides via env vars. This example works now but errored prior to this change:
```
$ env HOST_MONITORING::LOGS::INCLUDE='/test/file.txt,/file.log' ./observe-agent config
cloud_resource_detectors:
- ec2
self_monitoring:
enabled: true
enabled: true
logs:
enabled: true
include:
- /test/file.txt
- /file.log
metrics:
host:
enabled: true
```

fix: correctly handle viper env var overrides for slice fields

---

internal/connections/confighandler.go
packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

Clarify and expand the default env vars the agent provides to the configs. This makes the vanilla collector endpoint available as well as exposing the prometheus endpoint. It also renames OBSERVE_TOKEN to OBSERVE_AUTHORIZATION_HEADER for clarity since the value is prefixed by `"Bearer "`, and renames OBSERVE_ENDPOINT to OBSERVE_OTEL_ENDPOINT since the value is suffixed with `"/v2/otel"`

fix: clarify and expand the default env vars the agent provides to the configs

---

scripts/install_linux.sh

Update linux install to match mac install args. Also only run the `systemd` setup when `systemd` is available.

fix: update linux install to match mac install args

---

README.md

Add instructions for running the mac/linux install scripts off of local builds to the README.

feat: add instructions for running the mac/linux install scripts off of local builds to the README

---

Makefile

Check OS and arch in make install-ocb to get correct version. This now adds linux support.

fix: check OS and arch in make install-ocb to get correct version

---

scripts/install_linux.sh

Set up observe-agent service user in install_linux script. This now allows the script to work on a fresh install of Amazon Linux.

fix: set up observe-agent service user in install_linux script

---

scripts/install_mac.sh

Remove old bundled config files in mac install upgrade. I thought `cp -fR` would be sufficient, but that's not the case! I wasn't able to understand why the functionality is how it is, but here's a simple example to show the issue:
```sh
$ mkdir a && echo hello > a/test.txt && cp -R a b && cat b/test.txt
hello
$ echo goodbye > a/test.txt && cp -fR a b && cat b/test.txt 
hello
$ cat a/test.txt 
goodbye
```

fix: remove old bundled config files in mac install upgrade

---

internal/config/configschema.go
packaging/docker/observe-agent/connections/host_monitoring/logs.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/logs.yaml
packaging/macos/connections/host_monitoring/logs.yaml
scripts/install_mac.sh

OB-40414 Add exclude config option for excluding host log files.
Excerpt from `observe-agent config`:
```yml
enabled: true
logs:
enabled: true
exclude: [asdf.txt]
receivers:
filelog/host_monitoring:
include:
- /var/log/**/*.log
exclude:
- asdf.txt
include_file_path: true
storage: file_storage
retry_on_failure:
enabled: true
max_log_size: 4MiB
operators:
- type: filter
expr: 'body matches "otel-contrib"'
```

feat: add exclude config option for excluding host log files

---

packaging/docker/Dockerfile
packaging/docker/compose-linux-host.yaml
packaging/docker/observe-agent/connections/host_monitoring/host.yaml
packaging/docker/observe-agent/connections/host_monitoring/host_metrics.yaml
packaging/docker/observe-agent/connections/host_monitoring/process_metrics.yaml
packaging/docker/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/host.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/host_metrics.yaml
packaging/linux/etc/observe-agent/connections/host_monitoring/process_metrics.yaml
packaging/linux/etc/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/macos/connections/host_monitoring/host.yaml
packaging/macos/connections/host_monitoring/host_metrics.yaml
packaging/macos/connections/host_monitoring/process_metrics.yaml
packaging/macos/connections/self_monitoring/logs_and_metrics.yaml
packaging/windows/config/otel-collector.yaml
packaging/windows/connections/host_monitoring/host.yaml
packaging/windows/connections/host_monitoring/host_metrics.yaml
packaging/windows/connections/host_monitoring/logs.yaml
packaging/windows/connections/host_monitoring/process_metrics.yaml
packaging/windows/connections/self_monitoring/logs_and_metrics.yaml
packaging/windows/observe-agent.yaml

OB-40055 Update all bundled metrics configs to export Prometheus metrics.
I tested this with a direct write datastream and the metrics look good! I would love some advice on specific things to manually test, as this change won't be caught at all by our automated testing suite.

feat!: update all bundled metrics configs to export Prometheus metrics

---

scripts/install.ps1
scripts/install_linux.sh
scripts/install_mac.sh

OB-40308 add optional version arg to install scripts. This will allow our old Host Quickstart app installation instructions to be pinned to an older version as we update the agent.
Example usage:
```
PS C:\Users\Administrator\Downloads> .\install.ps1 -version 1.4.0
PS C:\Users\Administrator\Downloads> & 'C:\Program Files\Observe\observe-agent\observe-agent.exe' version
Using config file: C:\Program Files\Observe\observe-agent\observe-agent.yaml
observe-agent version: 1.4.0
```
```
$ bash ./scripts/install_mac.sh --version 1.5.0
Downloading version 1.5.0 from GitHub...
$ observe-agent version
observe-agent version: 1.5.0
observe-agent config file: /usr/local/observe-agent/observe-agent.yaml
```

feat: add optional version arg to install scripts

---

packaging/docker/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/linux/etc/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/macos/connections/self_monitoring/logs_and_metrics.yaml
packaging/windows/connections/self_monitoring/logs_and_metrics.yaml

Add file path to filelog/agent-config receiver. Our provided content extracts this field as a separate column, so we should set this attribute in all provided receivers.

fix: add file path to filelog/agent-config receiver

---

packaging/docker/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/connections/self_monitoring/logs_and_metrics.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/macos/connections/self_monitoring/logs_and_metrics.yaml
packaging/windows/config/otel-collector.yaml
packaging/windows/connections/self_monitoring/logs_and_metrics.yaml

Always put deltatocumulative processor before batch processor to keep batching as the last step.

fix: always put deltatocumulative processor before batch processor

---

README.md
go.mod
go.work
observecol/go.mod
vendor/github.com/docker/docker/api/swagger.yaml
vendor/github.com/docker/docker/api/types/container/hostconfig.go
vendor/modules.txt

Upgrade go version to 1.22.8
This also includes removing the go module replacements. I verified the high/critical CVEs are still fixed:
```
$ docker scout cves sha256:07a15d55106aded0734018ebd61141bfe3fa9b9aa99ae6dfe0261951540cceb3
✓ Image stored for indexing
✓ Indexed 405 packages
✓ Provenance obtained from attestation
✗ Detected 3 vulnerable packages with a total of 5 vulnerabilities
│                              Analyzed Image                                
────────────────────┼────────────────────────────────────────────────────────────────────────────
Target            │  sha256:07a15d55106aded0734018ebd61141bfe3fa9b9aa99ae6dfe0261951540cceb3   
digest          │  07a15d55106a                                                              
platform        │ linux/arm64 …
```

feat: upgrade go version to 1.22.8

---

packaging/macos/connections/self_monitoring/logs_and_metrics.yaml

Send logs/agent-config over otlp as intended. This pipeline was mistakenly switched to prometheus.

fix: send logs/agent-config over otlp as intended

---

internal/connections/confighandler.go

Ensure provided env var OBSERVE_COLLECTOR_URL never ends in a slash. Providing a consistent format regardless of how the agent is configured will make using this downstream easier and more reliable.

fix: ensure provided env var OBSERVE_COLLECTOR_URL never ends in a slash

---

packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

feat: tune memory limiter settings

---

.github/workflows/vuln-check.yaml

feat: add docker CVE's check action

feat: add docker CVE's check action

---

.github/workflows/release.yaml

In order to create a release on github, we need to create a git tag. This filter will ensure we don't trigger a real release when tagging a nightly release.

fix: do not create releases when tag is dev or nightly

---

.github/workflows/release-nightly.yaml
.github/workflows/release.yaml
.github/workflows/vuln-check.yaml

internal: add CVE check to release job as blocking

internal: add CVE check to release job as blocking

---

.github/workflows/generate-changelog.yaml
.github/workflows/release-build.yaml
.github/workflows/release-nightly.yaml
.github/workflows/release.yaml
.github/workflows/tests-integration.yaml
.github/workflows/vuln-check.yaml
.goreleaser.yaml
scripts/install.ps1
scripts/install_linux.sh
scripts/install_mac.sh

The objective of this change is to create github releases and publish docker images whenever we do a nightly build, but not tag either as `latest` (and instead use tag `dev-nightly`). Before this change: no github releases were published, and docker builds were published and tagged `latest`.

fix: make full use of nightly build functionality by publishing github releases and not tagging docker images as latest

---

.github/workflows/tests-integration.yaml
internal/commands/diagnose/authcheck.tmpl
internal/commands/diagnose/configcheck.tmpl
internal/commands/diagnose/otelconfigcheck.tmpl
internal/commands/status/status.go
internal/commands/status/status.tmpl
internal/connections/templatefuncs.go

Clean up spacing for diagnose and status output, move status to end of output.
Ex:
```
$ ./observe-agent status
Error getting agent metrics:  Get "http://localhost:8888/metrics": dial tcp 127.0.0.1:8888: connect: connection refused
================
Agent
================
Host Info
================
HostID: ...
Hostname: ...
BootTime: 2025-02-25T22:47:39-06:00
Uptime: 206h22m21s
OS: darwin
Platform: darwin
PlatformFamily: Standalone Workstation
PlatformVersion: 15.3.1
KernelArch: arm64
KernelVersion: 24.3.0
Agent Health
================
Status: NotRunning
```
or
```
$ ./observe-agent status
================
Agent
================
Host Info
================
HostID: ...
Hostname: ...
BootTime: 2025-02-25T22:47:39-06:00
Uptime: 206h25m34s
OS: darwin
Platform: darwin
PlatformFamily: Standalone …
```

fix: clean up spacing for diagnose and status output, move status to end of output

---

packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

Add default batch timeout of 5s to reduce number of requests.

feat: add default batch timeout of 5s

---

.github/workflows/release-nightly.yaml
packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/config/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

In order for the out of box routing to work, send all traces to shared "Tracing" package and all other data to host connection specific "Host Explorer".
In the future those will be configurable.
https://observe.atlassian.net/browse/OB-41698

Add default package routing headers

---

.github/workflows/release.yaml
.github/workflows/vuln-check-full.yaml
.github/workflows/vuln-check-release.yaml

Only block release on fixed issues with higher severity than low. This will ensure we can still release in the 180 day window we have to fix low severity issues, or when we know about an issue that has no fix.

fix: only block release on fixed issues with higher severity than low

---

.goreleaser.yaml

Using `{{ .CurrentTag }}` failed in the latest release: https://github.com/observeinc/observe-agent/actions/runs/13976540750/job/39131810187
`CurrentTag` came from the goreleaser release github docs: https://goreleaser.com/customization/release/#github
Looking at [the code](https://github.com/goreleaser/goreleaser/blob/f9bc1caafab4f949f849900e2219814c78adaf72/pkg/context/context.go#L88), I wonder if the actual value ought to be `{{ .Git.CurrentTag }}`. But there are no uses of `CurrentTag` in templates in their repo.
Many of their tests reference `Tag`, which is detailed in the docs here: https://goreleaser.com/customization/templates/#common-fields
I was convinced by the use of `Tag` in their tests, so that's what I decided to try first. Unfortunately this `release.tag` feature is only …

fix: use .Tag in goreleaser tag template

---

go.mod
internal/commands/config/config.go
observecol/otelcollector.go

Add the flags `--render-otel` and `--render-otel-details` to the `config` command to print full otel config. This short version is modeled after the `otelcol print` command, the long version was modeled after the startup command.
Ex:
```
$ ./observe-agent config --render-otel | tail -n 40
- debug
processors:
- filter/count
receivers:
- count
metrics/forward:
exporters:
- prometheusremotewrite/observe
processors:
- resourcedetection
- resourcedetection/cloud
- deltatocumulative
- batch
receivers:
- otlp
metrics/host_monitoring_host:
exporters:
- prometheusremotewrite/observe
processors:
- memory_limiter
- resourcedetection
- resourcedetection/cloud
- batch
receivers:
- hostmetrics/host-monitoring-host
traces/forward:
exporters:
- otlphttp/observetracing
processors:
- resourcedetection
- …
```

feat: add config command flag --render-otel to print full otel config

---

scripts/install.ps1
scripts/install_linux.sh
scripts/install_mac.sh

Make install scripts backwards compatible. This was accidentally broken in 97fbd007.

fix: make install scripts backwards compatible

---

internal/config/configschema.go
internal/root/root.go

Add viper defaults for all agent config settings. Without this, nested env vars will be ignored unless the value is already set in the config. ex: `env HOST_MONITORING::ENABLED=true ./observe-agent start` will be ignored with an empty agent config.

fix: add defaults for agent config to fully support nested env var overriders

---

internal/commands/status/statusretriever.go
internal/config/configschema.go
internal/connections/confighandler.go
packaging/docker/observe-agent/connections/common/internal_telemetry.yaml.tmpl
packaging/linux/connections/common/internal_telemetry.yaml.tmpl
packaging/macos/connections/common/internal_telemetry.yaml.tmpl
packaging/windows/connections/common/internal_telemetry.yaml.tmpl

Improve internal_telemetry agent configuration. Currently the only way in the agent to set logging to a level other than INFO or DEBUG is with custom otel config overrides. This allows for easy configuration via the agent config as well as respecting the env var `OTEL_LOG_LEVEL` if it's set outside the agent process.

feat: improve internal_telemetry agent configuration

---

internal/connections/confighandler.go

OB-42780: default the TRACE_TOKEN env var to be the agent token
I think this is the simplest solution and avoids a lot of k8s complexity.

feat: default the TRACE_TOKEN env var to be the agent token

---

internal/commands/start/start.go
packaging/docker/observe-agent/connections/common/base.yaml.tmpl
packaging/linux/connections/common/base.yaml.tmpl
packaging/macos/connections/common/base.yaml.tmpl
packaging/windows/connections/common/base.yaml.tmpl

add feature flag and parallelism config to PRWE

---

.github/workflows/generate-changelog.yaml
.github/workflows/orca.yaml
.github/workflows/release-build.yaml
.github/workflows/release-nightly.yaml
.github/workflows/release.yaml
.github/workflows/tests-integration.yaml
.github/workflows/vuln-check-full.yaml
.github/workflows/vuln-check-release.yaml

The latest release was canceled; this same timeout has been working for integration tests and nightly builds.

fix: bump goreleaser version and add explicit timeout to the release workflow

---

integration/scripts/requirements.txt
integration/scripts/snapshots/docker.yaml
integration/scripts/snapshots/full-agent-config.yaml
integration/scripts/snapshots/linux.yaml
integration/scripts/snapshots/windows.yaml
integration/scripts/test_snapshot_conf.py
integration/scripts/utils.py
integration/tests/integration.tftest.hcl
packaging/docker/observe-agent/connections/common/forward.yaml.tmpl

OB-45143 Add snapshot tests for the full bundled config in our test environments. This will catch when the observe-agent's provided otel config changes.

feat: add snapshot tests for bundled config

---

integration/scripts/snapshots/docker.yaml
integration/scripts/snapshots/full-agent-config.yaml
integration/scripts/snapshots/linux.yaml
internal/commands/initconfig/initconfig.go
internal/config/configschema.go
packaging/docker/observe-agent/connections/host_monitoring/logs.yaml.tmpl
packaging/linux/connections/host_monitoring/logs.yaml.tmpl
packaging/macos/connections/host_monitoring/logs.yaml.tmpl

feat: add default multiline autodetection

---

internal/commands/config/config_test.go
internal/commands/config/test/snap1-windows-output.yaml
internal/commands/config/test/snap2-windows-output.yaml
packaging/windows/connections/host_monitoring/logs.yaml.tmpl

OB-46154 enable filelog receiver in windows if `host_monitoring.logs.include` is specified.
Depends on #223

feat: enable filelog receiver in windows if include is specified

---

internal/commands/config/test/snap0-default-agent-config.yaml
internal/commands/config/test/snap0-docker-output.yaml
internal/commands/config/test/snap0-linux-output.yaml
internal/commands/config/test/snap0-macos-output.yaml
internal/commands/config/test/snap0-windows-output.yaml
internal/commands/config/test/snap1-docker-output.yaml
internal/commands/config/test/snap1-full-agent-config.yaml
internal/commands/config/test/snap1-linux-output.yaml
internal/commands/config/test/snap1-macos-output.yaml
internal/commands/config/test/snap1-windows-output.yaml
internal/commands/config/test/snap2-empty-agent-config.yaml
internal/config/configschema.go
internal/connections/bundledconfig/shared/common/internal_telemetry.yaml.tmpl
observe-agent.schema.json

This is the last internal telemetry option configurable in the helm chart but not in the agent (it's `agent.config.global.service.telemetry.loggingEncoding` in our helm chart).

feat: add log encoding config option for internal telemetry

---

.goreleaser.yaml
internal/commands/initconfig/writeconfigfile.go
packaging/linux/config/observe-agent.yaml
packaging/windows/observe-agent.yaml

IDEs check this to enforce yaml schema. I think that it is safe to release the schema for the first time in the same release that we set this comment, since the comment will not be in use until the schema is released.

feat: add the yaml schema comment to our default agent configs and init-config

---

internal/commands/config/config_test.go
internal/commands/config/test/snap2-otel-config.yaml
internal/commands/config/test/snap2-with-otel-output.yaml
observecol/otelcollector.go

Use "env" as the default config resolver schema so `${TOKEN}` in passed in config will read from an environment variable (just like `${env:TOKEN}`).

fix: use env as default config resolve schema

---

.github/workflows/release-nightly.yaml
.github/workflows/release.yaml

[OBSSD-1445](https://observe.atlassian.net/browse/OBSSD-1445) changing the goreleaser timeout since we just had it time out.
[OBSSD-1445]: https://observe.atlassian.net/browse/OBSSD-1445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move timeout from 25 minutes to 35 minutes

---

.github/workflows/orca.yaml
internal/commands/status/statusretriever.go
scripts/generate_jsonschema.go

This fixes most of the ORCA warnings that we have; the rest after this have to do with our docker image generation.

chore: ignore vendor files and test data in orca scans, clean up warnings
