observeinc/observe-agent

packaging/linux/scripts/preinstall.sh

fix: update command to work on debian + rhel in preinstall.sh

---

.goreleaser.yaml

fix: work around goreleaser

---

cmd/commands/initconfig/configschema.go
cmd/commands/initconfig/initconfig.go
cmd/commands/initconfig/initconfig_test.go
cmd/commands/initconfig/observe-agent.tmpl
packaging/linux/config/observe-agent.yaml

feat: add more flags to init-config

---

cmd/config/confighandler.go
packaging/linux/config/observe-agent.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/otel-collector.yaml
packaging/windows/config/otel-collector.yaml
packaging/windows/observe-agent.yaml

OB-32371 Add debug option to top level observe-agent.yaml config

feat: add debug option to top level config

---

.github/workflows/release.yml
.goreleaser.yaml
scripts/install.ps1

fix: revert goreleaser changes

---

.github/workflows/release-build.yml
.github/workflows/release.yml
.goreleaser.yaml

internal: upgrade goreleaser to v2.0.0

---

.goreleaser.yaml

internal: Add groupings to changelog

---

.github/workflows/tests-integration.yaml

chore: add integration test when push to main

---

packaging/docker/Dockerfile

OB-XXX Update Dockerfile to use alpine as base and expose some ports

fix: update dockerfile to add ports + alpine as base

---

packaging/docker/Dockerfile

OB-XXX Bump alpine version to 3.20.2

build(deps): bump alpine version to 3.20.2

---

packaging/docker/Dockerfile

Update the casing in the Dockerfile to resolve warnings

fix: update casing

---

.github/workflows/release-build.yaml
.github/workflows/release-nightly.yaml
.github/workflows/release.yaml

internal: update github runner used for releases

---

cmd/config/confighandler.go

internal: print out all config files used on startup

---

packaging/linux/config/observe-agent.yaml
packaging/windows/observe-agent.yaml

internal: update example otel_config_overrides to reflect new configs

---

Makefile
builder-config.yaml
cmd/collector/go.mod

OB-XXX Update makefile command to correct replace statement

internal: update makefile command for ocb build

---

components/processors/observek8sattributesprocessor/types.go

OB-0 remove unintended log lines

fix: rm debug log lines

---

packaging/docker/observe-agent/otel-collector.yaml
packaging/linux/etc/observe-agent/otel-collector.yaml
packaging/macos/otel-collector.yaml
packaging/windows/config/otel-collector.yaml

OB-36928: Switch from gzip to zstd compression

feat: switch from gzip to zstd

---

.github/workflows/release-nightly.yaml

Authorise Enrico Giorio to perform nightly releases

Authorize myself to perform nightly releases

---

.github/workflows/tests-integration.yaml

- Adds daily scheduled testing for integration tests

ci: add schedule for integration tests

---

integration/modules/create_ec2/locals.tf

Updates AMIs for Windows 2019 / 2022 to new supported IDs

ci: updates for windows 2019/2022 ami

---

.github/workflows/vuln-check.yaml

fix: update path for binary for vuln check

---

.github/workflows/tests-integration.yaml
.goreleaser.yaml

Add explicit timeout to observe-agent integration tests

fix: add explicit timeout to observe-agent integration tests

---

packaging/linux/config/observe-agent.service

Always restart linux systemd service

feat: always restart linux systemd service

---

components/processors/observek8sattributesprocessor/README.md

feat: add readme for k8sattributesprocessor

---

packaging/docker/observe-agent/connections/common/base.yaml.tmpl

use cgroup extension for container environments only

---

go.mod
vendor/github.com/go-viper/mapstructure/v2/.golangci.yaml
vendor/github.com/go-viper/mapstructure/v2/README.md
vendor/github.com/go-viper/mapstructure/v2/decode_hooks.go
vendor/github.com/go-viper/mapstructure/v2/errors.go
vendor/github.com/go-viper/mapstructure/v2/flake.lock
vendor/github.com/go-viper/mapstructure/v2/flake.nix
vendor/github.com/go-viper/mapstructure/v2/mapstructure.go
vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
vendor/github.com/pelletier/go-toml/v2/README.md
vendor/github.com/pelletier/go-toml/v2/marshaler.go
vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
vendor/github.com/sagikazarmark/locafero/flake.lock
vendor/github.com/sagikazarmark/locafero/flake.nix
vendor/github.com/spf13/afero/.editorconfig
vendor/github.com/spf13/afero/.golangci.yaml
vendor/github.com/spf13/afero/README.md
vendor/github.com/spf13/afero/iofs.go
vendor/github.com/spf13/afero/memmap.go
vendor/github.com/spf13/cast/README.md
vendor/github.com/spf13/cast/caste.go
vendor/github.com/spf13/viper/.golangci.yaml
vendor/github.com/spf13/viper/README.md
vendor/github.com/spf13/viper/UPDATES.md
vendor/github.com/spf13/viper/flake.lock
vendor/github.com/spf13/viper/flake.nix
vendor/github.com/spf13/viper/viper.go
vendor/modules.txt

The mapstructure update fixes a vulnerability.
Before:
https://github.com/observeinc/observe-agent/actions/runs/16356945962/job/46217424102
After:
https://github.com/observeinc/observe-agent/actions/runs/16357470462
(at the time of posting, the remaining vulns after this change remain unfixed)

chore: update viper and mapstructure dependencies

---

internal/commands/config/config_test.go
internal/commands/config/test/snap0-default-agent-config.yaml
internal/commands/config/test/snap0-docker-output.yaml
internal/commands/config/test/snap0-linux-output.yaml
internal/commands/config/test/snap0-macos-output.yaml
internal/commands/config/test/snap0-windows-output.yaml
internal/commands/config/test/snap1-docker-output.yaml
internal/commands/config/test/snap1-full-agent-config.yaml
internal/commands/config/test/snap1-linux-output.yaml
internal/commands/config/test/snap1-macos-output.yaml
internal/commands/config/test/snap1-windows-output.yaml
internal/commands/config/test/snap2-windows-output.yaml
internal/commands/config/test/snap2-with-otel-output.yaml
internal/config/configschema.go
internal/config/configschema_test.go
internal/connections/allconnectiontypes.go
internal/connections/bundledconfig/bundledconfig.go
internal/connections/bundledconfig/docker/common/base.yaml.tmpl
internal/connections/bundledconfig/shared/application/RED_metrics.yaml.tmpl
internal/connections/bundledconfig/shared/common/base.yaml.tmpl
internal/connections/bundledconfig/shared/common/forward.yaml.tmpl
internal/connections/bundledconfig/shared/templates.go
internal/connections/bundledconfig/windows/common/base.yaml.tmpl
observe-agent.schema.json
scripts/generate_jsonschema.go

This is similar to https://github.com/observeinc/helm-charts/pull/394 but with the k8s logic replaced by host resource detection.

feat: add an option to generate RED metrics from spans
